<?php

namespace App\Http\Controllers\Admin;

use App\Events\PostUpdated;
use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Tag;
use App\Services\CloudinaryService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * Admin\PostController — admin post management.
 *
 * Validates: Requirements 2
 */
class PostController extends Controller
{
    /**
     * GET /api/admin/posts
     *
     * Returns all posts (published + draft), paginated.
     *
     * Validates: Requirements 2.7
     */
    public function index(Request $request): JsonResponse
    {
        $query = Post::with(['tags', 'user'])
            ->withCount(['comments', 'likedByUsers as likes_count', 'favoritedByUsers as favorites_count'])
            ->orderByDesc('created_at');

        // Filtre par statut
        if ($request->filled('status')) {
            $query->where('status', $request->input('status'));
        }

        // Filtre par tag
        if ($request->filled('tag')) {
            $query->whereHas('tags', fn($q) => $q->where('slug', $request->input('tag')));
        }

        $posts = $query->paginate(10);

        return response()->json($posts);
    }

    /**
     * GET /api/admin/posts/{id}
     * Returns a single post by ID for the editor.
     */
    public function show(int $id): JsonResponse
    {
        $post = Post::with(['tags', 'user'])
            ->withCount(['comments', 'likedByUsers as likes_count', 'favoritedByUsers as favorites_count'])
            ->findOrFail($id);

        return response()->json($post);
    }

    /**
     * POST /api/admin/posts
     *
     * Creates a new post. Slug is auto-generated by the Post model.
     * Validates cover_image (image MIME, max 5MB).
     *
     * Validates: Requirements 2.1, 2.2, 2.10
     */
    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'title'       => 'required|string|max:255',
            'content'     => 'required|string',
            'status'      => 'sometimes|in:published,draft',
            'excerpt'     => 'nullable|string',
            'cover_image' => 'nullable|image|max:5120',
            'tags'        => 'nullable|array',
            'tags.*'      => 'string',
        ]);

        $coverImagePath = null;
        if ($request->hasFile('cover_image')) {
            $cloudinary = new CloudinaryService();
            $coverImagePath = $cloudinary->upload($request->file('cover_image'), 'covers');
        }

        $post = Post::create([
            'user_id'     => $request->user()->id,
            'title'       => $validated['title'],
            'content'     => $validated['content'],
            'status'      => $validated['status'] ?? 'draft',
            'excerpt'     => $validated['excerpt'] ?? null,
            'cover_image' => $coverImagePath,
            'published_at'=> isset($validated['status']) && $validated['status'] === 'published'
                                ? now()
                                : null,
        ]);

        // Associate tags (find or create by name)
        if (!empty($validated['tags'])) {
            $tagIds = $this->resolveTagIds($validated['tags']);
            $post->tags()->sync($tagIds);
        }

        $post->load(['tags', 'user']);

        return response()->json($post, 201);
    }

    /**
     * PUT /api/admin/posts/{id}
     *
     * Updates an existing post. Syncs tags if provided.
     *
     * Validates: Requirements 2.3
     */
    public function update(Request $request, int $id): JsonResponse
    {
        $post = Post::findOrFail($id);

        $validated = $request->validate([
            'title'       => 'sometimes|string|max:255',
            'content'     => 'sometimes|string',
            'status'      => 'sometimes|in:published,draft',
            'excerpt'     => 'nullable|string',
            'cover_image' => 'nullable|image|max:5120',
            'tags'        => 'nullable|array',
            'tags.*'      => 'string',
        ]);

        // Handle cover image replacement
        if ($request->hasFile('cover_image')) {
            // Remove old image from Cloudinary if it's a Cloudinary URL
            if ($post->cover_image && str_contains($post->cover_image, 'cloudinary.com')) {
                $cloudinary = new CloudinaryService();
                $cloudinary->delete($post->cover_image);
            } elseif ($post->cover_image && !str_starts_with($post->cover_image, 'http')) {
                Storage::disk('public')->delete($post->cover_image);
            }
            $cloudinary = new CloudinaryService();
            $validated['cover_image'] = $cloudinary->upload($request->file('cover_image'), 'covers');
        } else {
            unset($validated['cover_image']);
        }

        // When publishing (status changed to published), set published_at if not set
        if (isset($validated['status']) && $validated['status'] === 'published' && !$post->published_at) {
            $validated['published_at'] = now();
        }

        $post->update($validated);

        // Sync tags if provided
        if (array_key_exists('tags', $validated)) {
            if (!empty($validated['tags'])) {
                $tagIds = $this->resolveTagIds($validated['tags']);
                $post->tags()->sync($tagIds);
            } else {
                $post->tags()->detach();
            }
        }

        $post->load(['tags', 'user']);

        return response()->json($post);
    }

    /**
     * DELETE /api/admin/posts/{id}
     *
     * Deletes a post. Cascade handles comments, likes, favorites, and post_tag pivot.
     *
     * Validates: Requirements 2.4
     */
    public function destroy(int $id): JsonResponse
    {
        $post = Post::findOrFail($id);

        // Remove cover image from local storage if applicable
        if ($post->cover_image && !str_starts_with($post->cover_image, 'http')) {
            Storage::disk('public')->delete($post->cover_image);
        }

        $post->delete();

        return response()->json(null, 204);
    }

    /**
     * PATCH /api/admin/posts/{id}/pin
     *
     * Toggles the pinned state of a post. Fires PostUpdated.
     *
     * Validates: Requirements 2.6, 11.3
     */
    public function pin(Request $request, int $id): JsonResponse
    {
        $post = Post::findOrFail($id);

        $post->update(['pinned' => !$post->pinned]);

        event(new PostUpdated($post->fresh()));

        $post->load(['tags', 'user']);

        return response()->json($post);
    }

    /**
     * PATCH /api/admin/posts/{id}/publish
     *
     * Toggles post status between published and draft.
     * Sets published_at when transitioning to published.
     * Fires PostUpdated.
     *
     * Validates: Requirements 2.5, 11.3
     */
    public function publish(Request $request, int $id): JsonResponse
    {
        $post = Post::findOrFail($id);

        if ($post->status === 'published') {
            $post->update(['status' => 'draft']);
        } else {
            $post->update([
                'status'       => 'published',
                'published_at' => $post->published_at ?? now(),
            ]);
        }

        event(new PostUpdated($post->fresh()));

        $post->load(['tags', 'user']);

        return response()->json($post);
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Resolve tag names to their IDs, creating any that don't exist.
     *
     * @param  array<string>  $names
     * @return array<int>
     */
    private function resolveTagIds(array $names): array
    {
        return array_map(function (string $name) {
            $tag = Tag::firstOrCreate(
                ['slug' => Str::slug($name)],
                ['name' => $name]
            );
            return $tag->id;
        }, $names);
    }
}
